name: Test

on: push

jobs:
  test:
    runs-on: ${{matrix.os}}
    name: ${{matrix.os}} / OTP ${{matrix.pair.otp-version}} / Elixir ${{matrix.pair.elixir-version}}
    strategy:
      matrix:
        # FIXME os: [ubuntu-latest, windows-latest]
        os: [windows-latest]
        pair:
          # Full Versions
          - otp-version: 22.0
            elixir-version: 1.9.1
          # Semver ranges
          # FIXME - otp-version: 21.x
          # FIXME   elixir-version: <1.9.1
          # FIXME # Branches
          # FIXME - otp-version: 22.0
          # FIXME   elixir-version: master
    steps:
      - uses: actions/checkout@v1.0.0
      - name: Use actions/setup-elixir
        uses: ./
        with:
          otp-version: ${{matrix.pair.otp-version}}
          elixir-version: ${{matrix.pair.elixir-version}}
      - name: Run Mix project tests
        run: |-
          cd test-project
          mix deps.get
          mix test
